### ISSUE TITLE
不是很明白// Prevent electron-builder from installing app deps  

### ISSUE THREAD

**Issue by 303182519** [liangskyli/umi-electron#1]
// Prevent electron-builder from installing app deps
  fsExtra.ensureDirSync(`${absOutputDir}/bundled/node_modules`);
  上面的这个是阻止electron-builder进行下载，为什么要阻止呢？
假如阻止的话，这样不就是导致electron配置参数externals无法下载了吗，假如主进程用到sqlite3

**Comment by liangskyli** [comment]
不会，externals里配置了sqlite3，打包后，node_modules会有sqlite3，如有问题，可以给最小复现
